### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by alignwaivers** [CircuitMess/Jay-D#1]
Seems like a really great idea!
I see circuitmess has some things that are open source, and just curious what is the licensing for this project. Also, it's not totally clear, is this the code for the board itself? Wondering what the software is for programming it as well. Thanks!

**Comment by filipbudisa** [comment]
Hello!

This is the repo for the legacy Jay-D code, used during the prototype phase, and is licensed under the MIT license.
The current repos for the firmware and library are [CircuitMess/JayD-Library](https://github.com/CircuitMess/JayD-Library), [CircuitMess/JayD-Firmware](https://github.com/CircuitMess/JayD-Firmware), and [CircuitMess/JayD-Nuvoton-Firmware](https://github.com/CircuitMess/JayD-Nuvoton-Firmware), also under the MIT license.

The library and firmware are for the Jay-D board, but you can use parts of the library on other ESP32 boards. The Nuvoton-Firmware is for the Nuvoton N76E616 MCU on the board offloading the input processing.

Filip
